version: '2'
services:
  sampleapp:
    image: darkxahtep/docker-itshare-sampleapp:5
    container_name: docker-itshare-sampleapp
    restart: always
    environment:
      VIRTUAL_HOST: sampleapp.darkxahtep.co.ua
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: sampleapp.darkxahtep.co.ua
      LETSENCRYPT_EMAIL: darkxahtep@gmail.com
      ConnectionStrings__Word_DB: ${ConnectionStrings__Word_DB}
    links:
      - sqlserver
    depends_on:
      - sqlserver
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: docker-itshare-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: docker-itshare-letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - nginx-proxy
    depends_on:
      - nginx-proxy
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU13-ubuntu
    container_name: docker-itshare-sqlserver
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: $SQLSERVER_SA_PASSWORD
      MSSQL_PID: Developer
    volumes:
      - sqldata:/var/opt/mssql
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  sqldata:
